language: php
php:
  - "7.3"
dist: bionic
before_install:
  - sudo apt-get update
  - ./install.sh apacheServer
  - export phpInstaller="curl --silent --show-error https://raw.githubusercontent.com/davidkhala/ubuntu-utils/master/php.sh"
  - $phpInstaller | bash -s installDevPack
  - $phpInstaller | bash -s installApacheInterpretor
  - $phpInstaller | bash -s installMySQLConnector
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod proxy_fcgi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo service apache2 restart
  - ./install.sh MySQL
  - sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'";sudo systemctl restart mysql;
install:
  - ./install.sh phpComposer
  - cd redbean; composer install --no-interaction; cd -
  - cd slim; composer install --no-interaction; cd -
script:
  - cd redbean; phpunit --bootstrap vendor/autoload.php tests; cd -
  - cd slim; php ./tests/app.php ; cd -
